/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dotsPack;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author G50
 */
public class AnimatedFraamy extends javax.swing.JFrame {

    private static int ball = 1;
    private javax.swing.Timer timer;

    /**
     * Creates new form dotsFrame
     */
    public AnimatedFraamy() {
        initComponents();

        k1.setVisible(false);
        k2.setVisible(false);
        k3.setVisible(false);
        k4.setVisible(false);
        k5.setVisible(false);
        k6.setVisible(false);
        k7.setVisible(false);
        k8.setVisible(false);
        k9.setVisible(false);
        k10.setVisible(false);
        k11.setVisible(false);
        k12.setVisible(false);
        k13.setVisible(false);
        k14.setVisible(false);
        k15.setVisible(false);
        k16.setVisible(false);
        k17.setVisible(false);
        k18.setVisible(false);
        k19.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        k5 = new javax.swing.JLabel();
        k6 = new javax.swing.JLabel();
        k7 = new javax.swing.JLabel();
        k8 = new javax.swing.JLabel();
        k9 = new javax.swing.JLabel();
        k10 = new javax.swing.JLabel();
        k11 = new javax.swing.JLabel();
        k12 = new javax.swing.JLabel();
        k13 = new javax.swing.JLabel();
        k14 = new javax.swing.JLabel();
        k15 = new javax.swing.JLabel();
        k16 = new javax.swing.JLabel();
        k17 = new javax.swing.JLabel();
        k18 = new javax.swing.JLabel();
        k19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"The heart of programming\"");
        setBackground(new java.awt.Color(153, 0, 153));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        k2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        k3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        k4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        k5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        k6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        k7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        k8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        k9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        k10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        k11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        k12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        k13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        k14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        k15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        k16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        k17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        k18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        k19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsPack/juju.png"))); // NOI18N
        jPanel1.add(k19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        timer = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                switch (ball) {
                    case 1:
                        k1.setVisible(true);
                      k15.setVisible(false);
                        break;
                    case 2:
                        k2.setVisible(true);
                        k16.setVisible(false);
                        break;
                    case 3:
                        k3.setVisible(true);
                        k17.setVisible(false);
                        break;
                    case 4:
                        k4.setVisible(true);
                        k18.setVisible(false);
                        break;
                    case 5:
                        k5.setVisible(true);
                        k19.setVisible(false);
                        break;
                    case 6:
                        k6.setVisible(true);
                        k1.setVisible(false);
                        break;
                    case 7:
                        k7.setVisible(true);
                        k2.setVisible(false);
                        break;
                    case 8:
                        k8.setVisible(true);
                        k3.setVisible(false);
                        break;
                    case 9:
                        k9.setVisible(true);
                        k4.setVisible(false);
                        break;
                    case 10:
                        k10.setVisible(true);
                        k5.setVisible(false);
                        break;
                    case 11:
                        k11.setVisible(true);
                        k6.setVisible(false);
                        break;
                    case 12:
                        k12.setVisible(true);
                        k7.setVisible(false);
                        break;
                    case 13:
                        k13.setVisible(true);
                        k8.setVisible(false);
                        break;
                    case 14:
                        k14.setVisible(true);
                        k9.setVisible(false);
                        break;
                    case 15:
                        k15.setVisible(true);
                        k10.setVisible(false);
                        break;
                    case 16:
                        // try{Thread.sleep(300);}catch(Exception e){}
                        k16.setVisible(true);
                        k11.setVisible(false);
                        break;
                    case 17:
                        k17.setVisible(true);
                        k12.setVisible(false);
                        break;
                    case 18:
                        k18.setVisible(true);
                        k13.setVisible(false);
                        break;
                    case 19:
                        k19.setVisible(true);
                     k1.setVisible(false);
                    k14.setVisible(false);
                        break;

                }
                if (ball == 19) {
                    ball = 0;

                }
                ball++;
            }
        });
        timer.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimatedFraamy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimatedFraamy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimatedFraamy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimatedFraamy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimatedFraamy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k10;
    private javax.swing.JLabel k11;
    private javax.swing.JLabel k12;
    private javax.swing.JLabel k13;
    private javax.swing.JLabel k14;
    private javax.swing.JLabel k15;
    private javax.swing.JLabel k16;
    private javax.swing.JLabel k17;
    private javax.swing.JLabel k18;
    private javax.swing.JLabel k19;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel k7;
    private javax.swing.JLabel k8;
    private javax.swing.JLabel k9;
    // End of variables declaration//GEN-END:variables
}
